### ISSUE TITLE
Drive GDB remote serial protocol directly

### ISSUE THREAD

**Issue by pedrolamarao** [pedrolamarao/psys#132]
Currently, I am facing issues debugging an image which runs in a x86-64 emulator in protected mode. The debugger is confused by the fact that the image is  ELF32 i386 but the machine announces itself as x86_64.

Instead of fighting the gdb program, let us drive the remote serial protocol directly. This would allows us to interpret the target's messages with a richer context (we know we are running in x86 legacy mode or compatibility mode) and it would have the secondary benefit of removing an external dependency.

**Comment by pedrolamarao** [comment]
- [ ] create GDB remote protocol support library
- [ ] create ELF support library
- [ ] parse symbol table for position dependent ELF images
- [ ] drive GDB remote protocol to break in position dependent Multiboot2 ELF application
- [ ] rewrite psys test driver to drive GDB remote protocol directly
